set names utf8mb4;
set charset utf8mb4;

drop database if exists nederland;

create database nederland charset utf8mb4;

use nederland;

create table woonplaatsen
(
  id int unsigned not null primary key auto_increment,
  naam varchar(50) not null
);
insert into woonplaatsen(naam) values
('Almelo'),
('Veere'),
('Coevorden'),
('Aalsmeer'),
('Haarlemmermeer'),
('Zaltbommel'),
('Noardeast-Fryslân'),
('Aalten'),
('Nieuwkoop'),
('Assen'),
('Sluis'),
('Alphen aan den Rijn'),
('Laarbeek'),
('Opmeer'),
('Súdwest-Fryslân'),
('Medemblik'),
('Nissewaard'),
('De Ronde Venen'),
('Waadhoeke'),
('Barneveld'),
('Leusden'),
('Goeree-Overflakkee'),
('Zundert'),
('West Betuwe'),
('Het Hogeland'),
('Westerkwartier'),
('Bloemendaal'),
('Zevenaar'),
('Druten'),
('Bergen'),
('Dinkelland'),
('Castricum'),
('Heerenveen'),
('De Fryske Marren'),
('Tubbergen'),
('Alblasserdam'),
('Leeuwarden'),
('Tytsjerksteradiel'),
('Maasdriel'),
('Alkmaar'),
('Lochem'),
('Almere'),
('Altena'),
('West Maas en Waal'),
('Alphen-Chaam'),
('Noordenveld'),
('Stadskanaal'),
('De Wolden'),
('Hoogeveen'),
('Hof van Twente'),
('Vijfheerenlanden'),
('Aa en Hunze'),
('Horst aan de Maas'),
('Utrechtse Heuvelrug'),
('Amersfoort'),
('Krimpenerwaard'),
('Amstelveen'),
('Beekdaelen'),
('Amsterdam'),
('Ouder-Amstel'),
('Overbetuwe'),
('Hardenberg'),
('Lingewaard'),
('Wijdemeren'),
('Hollands Kroon'),
('Westerveld'),
('Westerwolde'),
('Apeldoorn'),
('Ooststellingwerf'),
('Appingedam'),
('Venlo'),
('Molenlanden'),
('Middelburg'),
('Arnhem'),
('Ommen'),
('Buren'),
('Zaanstad'),
('Asten'),
('Achtkarspelen'),
('Zeist'),
('Koggenland'),
('Terneuzen'),
('Montferland'),
('Terschelling'),
('Bronckhorst'),
('Borsele'),
('Baarle-Nassau'),
('Peel en Maas'),
('Steenwijkerland'),
('Baarn'),
('Oldambt'),
('Leudal'),
('Gemert-Bakel'),
('Opsterland'),
('Wijchen'),
('Midden-Drenthe'),
('Ameland'),
('Simpelveld'),
('Eijsden-Margraten'),
('Noordoostpolder'),
('Barendrecht'),
('Emmen'),
('Deventer'),
('Breda'),
('Maasgouw'),
('Beek'),
('Berg en Dal'),
('Cuijk'),
('Beesel'),
('Edam-Volendam'),
('Berkelland'),
('Ede'),
('Lopik'),
('Zandvoort'),
('Valkenburg aan de Geul'),
('Bergeijk'),
('Bergen op Zoom'),
('Oss'),
('Lansingerland'),
('Tilburg'),
('Sint-Michielsgestel'),
('Best'),
('Boxmeer'),
('Losser'),
('Beuningen'),
('Gulpen-Wittem'),
('Beverwijk'),
('Dronten'),
('Delfzijl'),
('Hilvarenbeek'),
('Haaren'),
('De Bilt'),
('Bladel'),
('Blaricum'),
('Weststellingwerf'),
('Venray'),
('Hoorn'),
('Bodegraven-Reeuwijk'),
('Boekel'),
('Groningen'),
('Smallingerland'),
('Borger-Odoorn'),
('Midden-Groningen'),
('Veendam'),
('Sittard-Geleen'),
('Borne'),
('Halderberge'),
('Rotterdam'),
('Stede Broec'),
('Boxtel'),
('Oude IJsselstreek'),
('Stichtse Vecht'),
('Brielle'),
('Waterland'),
('Langedijk'),
('Meppel'),
('Raalte'),
('Dantumadiel'),
('Schouwen-Duiveland'),
('Twenterand'),
('Brummen'),
('Brunssum'),
('Cranendonck'),
('Meerssen'),
('Tynaarlo'),
('Bunnik'),
('Bunschoten'),
('Texel'),
('Schagen'),
('Gooise Meren'),
('Capelle aan den IJssel'),
('Hulst'),
('Noord-Beveland'),
('Wijk bij Duurstede'),
('Vught'),
('Culemborg'),
('Hellendoorn'),
('Gorinchem'),
('Dalfsen'),
('Pijnacker-Nootdorp'),
('Delft'),
('Deurne'),
('Oldenzaal'),
('Diemen'),
('Rheden'),
('Steenbergen'),
('Neder-Betuwe'),
('Doesburg'),
('Doetinchem'),
('Heusden'),
('Dongen'),
('Elburg'),
('Renkum'),
('Dordrecht'),
('Oosterhout'),
('Velsen'),
('Drimmelen'),
('Duiven'),
('Eersel'),
('Echt-Susteren'),
('Eemnes'),
('Loppersum'),
('Eindhoven'),
('Stein'),
('Nunspeet'),
('Rhenen'),
('Epe'),
('Enkhuizen'),
('Enschede'),
('Wierden'),
('Ermelo'),
('Meierijstad'),
('Grave'),
('Etten-Leur'),
('Kerkrade'),
('Moerdijk'),
('Geertruidenberg'),
('Zoeterwoude'),
('Geldrop-Mierlo'),
('Zwartewaterland'),
('Gennep'),
('Gilze en Rijen'),
('Goes'),
('Goirle'),
('Gouda'),
('Hoeksche Waard'),
('Houten'),
('Kampen'),
('''s-Gravenhage'),
('Westland'),
('Oost Gelre'),
('Haaksbergen'),
('Haarlem'),
('Utrecht'),
('Reimerswaal'),
('Harderwijk'),
('Hardinxveld-Giessendam'),
('Harlingen'),
('Woerden'),
('Hattem'),
('Oldebroek'),
('Heemskerk'),
('Heemstede'),
('Heerde'),
('Heerhugowaard'),
('Zwijndrecht'),
('Roosendaal'),
('Heerlen'),
('Bernheze'),
('Heeze-Leende'),
('Heiloo'),
('Oudewater'),
('Den Helder'),
('Hellevoetsluis'),
('Helmond'),
('Drechterland'),
('Hendrik-Ido-Ambacht'),
('Hengelo'),
('Roerdalen'),
('Roermond'),
('''s-Hertogenbosch'),
('Oisterwijk'),
('Heumen'),
('Hillegom'),
('Hilversum'),
('Nijkerk'),
('Rijssen-Holten'),
('Reusel-De Mierden'),
('Woensdrecht'),
('Kaag en Braassem'),
('Midden-Delfland'),
('Huizen'),
('Staphorst'),
('IJsselstein'),
('Landsmeer'),
('Wormerland'),
('Loon op Zand'),
('Tiel'),
('Kapelle'),
('Katwijk'),
('Voorst'),
('Voerendaal'),
('Krimpen aan den IJssel'),
('Uithoorn'),
('Landgraaf'),
('Sint Anthonis'),
('Mill en Sint Hubert'),
('Laren'),
('Leiden'),
('Leiderdorp'),
('Leidschendam-Voorburg'),
('Lelystad'),
('Vaals'),
('Nijmegen'),
('Nederweert'),
('Someren'),
('Montfoort'),
('Lisse'),
('Maassluis'),
('Maastricht'),
('Olst-Wijhe'),
('Mook en Middelaar'),
('Beemster'),
('Zuidplas'),
('Pekela'),
('Nieuwegein'),
('Noordwijk'),
('Nuenen, Gerwen en Nederwetten'),
('Uden'),
('Oegstgeest'),
('Oirschot'),
('Vlissingen'),
('Westvoorne'),
('Oostzaan'),
('Tholen'),
('Papendrecht'),
('Albrandswaard'),
('Purmerend'),
('Putten'),
('Landerd'),
('Renswoude'),
('Ridderkerk'),
('Rijswijk'),
('Rozendaal'),
('Rucphen'),
('Teylingen'),
('Scherpenzeel'),
('Schiedam'),
('Schiermonnikoog'),
('Sliedrecht'),
('Soest'),
('Son en Breugel'),
('Waalwijk'),
('Weert'),
('Uitgeest'),
('Urk'),
('Valkenswaard'),
('Veenendaal'),
('Veldhoven'),
('Vlaardingen'),
('Vlieland'),
('Voorschoten'),
('Waalre'),
('Waddinxveen'),
('Wageningen'),
('Zutphen'),
('Wassenaar'),
('Weesp'),
('Westervoort'),
('Winterswijk'),
('Woudenberg'),
('Zeewolde'),
('Zoetermeer'),
('Zwolle');
create user if not exists cursist identified by 'cursist';
grant select on woonplaatsen to cursist;
